---
title: "EX1_ANSWERS_RU_tidyverse_dplyr_select_and_filter"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/RU_tidyverse/"
output: 
  html_document:
    toc: true # table of contents true
    toc_float: yes
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---
<p>&nbsp;</p>
These exercises cover the sections of [Data wrangling with tidy](https://rockefelleruniversity.github.io/RU_tidyverse/). 

All files can be found in the "dataset" directory.
<p>&nbsp;</p>
# **Exercise 1**  
<p>&nbsp;</p>
1. Create a dataframe with the variables _age_ and _IGF_ for only the _Steelhead_ fish
2. Create a dataframe with all the variables except the _IGF_ values, for all fish that begin with _S_

# ANSWERS

## Load in dataset
```{r}
load(file='dataset/my_tidy.Rdata')
library(tidyverse)
```

## Answer for Q1
```{r}
# Create a dataframe of the variables _age_ and _IGF_ of only the _Steelhead_ fish
df1_A <- filter(df1, common_name == 'Steelhead')
select(df1_A, age_classbylength, IGF1_ng_ml)
```
## Answer for Q2
```{r}
# Create a dataframe of all variables but the _IGF_ values, for all fish that begin with _S_
df1_A <- filter(df1, str_starts(common_name,'S'))
select(df1_A, -IGF1_ng_ml)
```
