---
title: "EX5_ANSWERS_RU_tidyverse_readr"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/RU_tidyverse/"
output: 
  html_document:
    toc: true # table of contents true
    toc_float: yes
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---
<p>&nbsp;</p>
These exercises cover the sections of [Data wrangling with tidy](https://rockefelleruniversity.github.io/RU_tidyverse/). 

All files can be found in the "dataset" directory.
<p>&nbsp;</p>
**Exercise 5**  
<p>&nbsp;</p>
* Read in count data as different data types. What happens when we extract the vector of these counts?

# ANSWERS

## Load in dataset and packages
```{r}
library(tidyverse)
```

## Answer
```{r}
untidy_counts_test <- read_csv("dataset/hemato_rnaseq_counts.csv", col_types = cols(
    ENTREZ = col_character(),
    CD34_1 = col_integer(),
    ORTHO_1 = col_character(),
    CD34_2 = col_factor(),
    ORTHO_2 = col_logical()
  ))

untidy_counts_test$CD34_1 %>% head(n=8)
untidy_counts_test$ORTHO_1 %>% head(n=8)
untidy_counts_test$CD34_2 %>% head(n=8)
untidy_counts_test$ORTHO_2 %>% head(n=8)
```

