---
title: "EX6_ANSWERS_RU_tidyverse_tidying"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/RU_tidyverse/"
output: 
  html_document:
    toc: true # table of contents true
    toc_float: yes
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---
<p>&nbsp;</p>
These exercises cover the sections of [Data wrangling with tidy](https://rockefelleruniversity.github.io/RU_tidyverse/). 

All files can be found in the "dataset" directory.
<p>&nbsp;</p>
**Exercise 6**  
<p>&nbsp;</p>
* tidy up df2

# ANSWERS

## Load in dataset and packages
```{r}
load(file='dataset/my_tidy.Rdata')
library(tidyverse)
```

## Answer
```{r}
df2 %>% 
  spread(value = value, key = variable)

df2 %>%
  pivot_wider(names_from = variable, values_from = value)

```

